/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddOnRevenue } from './models/AddOnRevenue';
export type { AddOnsManyResponse } from './models/AddOnsManyResponse';
export type { AddOnsResponse } from './models/AddOnsResponse';
export type { AuditLogManyResponse } from './models/AuditLogManyResponse';
export type { AuditLogResponse } from './models/AuditLogResponse';
export type { BrandManyResponse } from './models/BrandManyResponse';
export type { BrandResponse } from './models/BrandResponse';
export type { CalculateTotalDto } from './models/CalculateTotalDto';
export type { CardStatsResponse } from './models/CardStatsResponse';
export type { CarResponse } from './models/CarResponse';
export { CarType } from './models/CarType';
export type { CompletionRatioResponse } from './models/CompletionRatioResponse';
export type { CreateAddOnDto } from './models/CreateAddOnDto';
export type { CreateBrandDto } from './models/CreateBrandDto';
export type { CreateCarDto } from './models/CreateCarDto';
export type { CreateCustomerDto } from './models/CreateCustomerDto';
export type { CreateModelDto } from './models/CreateModelDto';
export type { CreateServiceDto } from './models/CreateServiceDto';
export type { CreateSuperVisorDto } from './models/CreateSuperVisorDto';
export type { CreateTechnicianDto } from './models/CreateTechnicianDto';
export type { CreateTransactionDto } from './models/CreateTransactionDto';
export type { CustomerResponse } from './models/CustomerResponse';
export type { CustomersManyResponse } from './models/CustomersManyResponse';
export type { ImageResponse } from './models/ImageResponse';
export type { InvoiceResponse } from './models/InvoiceResponse';
export { ModelResponse } from './models/ModelResponse';
export type { PeakAnalysisResponse } from './models/PeakAnalysisResponse';
export type { PeakDaysResponse } from './models/PeakDaysResponse';
export type { PeakHoursResponse } from './models/PeakHoursResponse';
export { PriceByCarType } from './models/PriceByCarType';
export type { RevenueSummary } from './models/RevenueSummary';
export { ServicePriceDto } from './models/ServicePriceDto';
export type { ServiceResponse } from './models/ServiceResponse';
export type { ServiceRevenue } from './models/ServiceRevenue';
export type { ServiceStageBottleneckResponse } from './models/ServiceStageBottleneckResponse';
export type { SigninDto } from './models/SigninDto';
export { SignupDto } from './models/SignupDto';
export type { SupervisorManyResponse } from './models/SupervisorManyResponse';
export type { SupervisorResponse } from './models/SupervisorResponse';
export type { TechnicianManyResponse } from './models/TechnicianManyResponse';
export type { TechnicianResponse } from './models/TechnicianResponse';
export type { TechnicianUtilizationResponse } from './models/TechnicianUtilizationResponse';
export type { TopCustomer } from './models/TopCustomer';
export type { TransactionManyResponse } from './models/TransactionManyResponse';
export { TransactionResponse } from './models/TransactionResponse';
export type { UpdateCustomerDto } from './models/UpdateCustomerDto';
export { UpdateTransactionDto } from './models/UpdateTransactionDto';
export { UserInfoResponse } from './models/UserInfoResponse';

export { AddOnsService } from './services/AddOnsService';
export { AppService } from './services/AppService';
export { AuditLogService } from './services/AuditLogService';
export { AuthService } from './services/AuthService';
export { BrandService } from './services/BrandService';
export { CarService } from './services/CarService';
export { CustomerService } from './services/CustomerService';
export { ImageService } from './services/ImageService';
export { ModelService } from './services/ModelService';
export { SeederService } from './services/SeederService';
export { ServiceService } from './services/ServiceService';
export { StatisticsService } from './services/StatisticsService';
export { SupervisorService } from './services/SupervisorService';
export { TechnicianService } from './services/TechnicianService';
export { TransactionService } from './services/TransactionService';
