/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActivateSubscriptionDto } from './models/ActivateSubscriptionDto';
export type { AddOnRevenue } from './models/AddOnRevenue';
export type { AddOnsManyResponse } from './models/AddOnsManyResponse';
export type { AddOnsResponse } from './models/AddOnsResponse';
export type { AllCustomerSubscriptionsResponseDto } from './models/AllCustomerSubscriptionsResponseDto';
export type { AssignQRCodeDto } from './models/AssignQRCodeDto';
export { AssignTechnicianToPhaseDto } from './models/AssignTechnicianToPhaseDto';
export type { AuditLogManyResponse } from './models/AuditLogManyResponse';
export type { AuditLogResponse } from './models/AuditLogResponse';
export type { BrandManyResponse } from './models/BrandManyResponse';
export type { BrandResponse } from './models/BrandResponse';
export type { CalculateTotalDto } from './models/CalculateTotalDto';
export type { CancelTransactionDto } from './models/CancelTransactionDto';
export type { CarBrandDto } from './models/CarBrandDto';
export type { CardStatsResponse } from './models/CardStatsResponse';
export type { CarInfoDto } from './models/CarInfoDto';
export { CarModelDto } from './models/CarModelDto';
export type { CarResponse } from './models/CarResponse';
export { CarType } from './models/CarType';
export type { CashSummary } from './models/CashSummary';
export type { CompletionRatioResponse } from './models/CompletionRatioResponse';
export type { CreateAddOnDto } from './models/CreateAddOnDto';
export type { CreateBrandDto } from './models/CreateBrandDto';
export type { CreateCarDto } from './models/CreateCarDto';
export type { CreateCustomerDto } from './models/CreateCustomerDto';
export type { CreateDailyNoteDto } from './models/CreateDailyNoteDto';
export type { CreateModelDto } from './models/CreateModelDto';
export type { CreateSalesDto } from './models/CreateSalesDto';
export type { CreateServiceDto } from './models/CreateServiceDto';
export type { CreateSubscriptionDto } from './models/CreateSubscriptionDto';
export type { CreateTechnicianDto } from './models/CreateTechnicianDto';
export type { CreateTransactionDto } from './models/CreateTransactionDto';
export type { CustomerInfoDto } from './models/CustomerInfoDto';
export type { CustomerResponse } from './models/CustomerResponse';
export type { CustomersManyResponse } from './models/CustomersManyResponse';
export type { CustomerSubscriptionResponseDto } from './models/CustomerSubscriptionResponseDto';
export type { CustomerVisitsResponse } from './models/CustomerVisitsResponse';
export type { DailyNoteResponse } from './models/DailyNoteResponse';
export type { DailyNotesListResponse } from './models/DailyNotesListResponse';
export type { DailyReportResponseDto } from './models/DailyReportResponseDto';
export type { DailySubscriptionRevenueResponse } from './models/DailySubscriptionRevenueResponse';
export type { DeleteUserDto } from './models/DeleteUserDto';
export type { EditScheduledTransactionDto } from './models/EditScheduledTransactionDto';
export { ImageResponse } from './models/ImageResponse';
export type { InvoiceResponse } from './models/InvoiceResponse';
export { ModelResponse } from './models/ModelResponse';
export type { NewCustomerResponse } from './models/NewCustomerResponse';
export type { PeakAnalysisResponse } from './models/PeakAnalysisResponse';
export type { PeakDaysResponse } from './models/PeakDaysResponse';
export type { PeakHoursResponse } from './models/PeakHoursResponse';
export { PriceByCarType } from './models/PriceByCarType';
export type { PurchaseSubscriptionDto } from './models/PurchaseSubscriptionDto';
export type { RemainingServiceDto } from './models/RemainingServiceDto';
export type { ResetPasswordDto } from './models/ResetPasswordDto';
export type { RevenueSummary } from './models/RevenueSummary';
export type { SalesManyResponse } from './models/SalesManyResponse';
export type { SalesResponse } from './models/SalesResponse';
export type { ServiceCarTypeRevenueResponse } from './models/ServiceCarTypeRevenueResponse';
export { ServicePriceDto } from './models/ServicePriceDto';
export type { ServiceResponse } from './models/ServiceResponse';
export type { ServiceRevenue } from './models/ServiceRevenue';
export type { ServiceStageBottleneckResponse } from './models/ServiceStageBottleneckResponse';
export type { SigninDto } from './models/SigninDto';
export { SignupDto } from './models/SignupDto';
export type { SubscriptionBasicInfoDto } from './models/SubscriptionBasicInfoDto';
export type { SubscriptionDatesDto } from './models/SubscriptionDatesDto';
export { SubscriptionPriceDto } from './models/SubscriptionPriceDto';
export { SubscriptionPriceResponseDto } from './models/SubscriptionPriceResponseDto';
export type { SubscriptionPricingDto } from './models/SubscriptionPricingDto';
export type { SubscriptionResponseDto } from './models/SubscriptionResponseDto';
export type { SubscriptionServiceDto } from './models/SubscriptionServiceDto';
export type { SubscriptionServiceResponseDto } from './models/SubscriptionServiceResponseDto';
export type { SubscriptionServicesUsageResponse } from './models/SubscriptionServicesUsageResponse';
export type { SubscriptionStatisticsResponse } from './models/SubscriptionStatisticsResponse';
export type { SubscriptionStatusDto } from './models/SubscriptionStatusDto';
export type { TechnicianManyResponse } from './models/TechnicianManyResponse';
export type { TechnicianResponse } from './models/TechnicianResponse';
export type { TechnicianShiftReport } from './models/TechnicianShiftReport';
export type { TechnicianUtilizationResponse } from './models/TechnicianUtilizationResponse';
export type { ToggleBlacklistDto } from './models/ToggleBlacklistDto';
export type { TopCustomer } from './models/TopCustomer';
export type { TransactionManyResponse } from './models/TransactionManyResponse';
export { TransactionResponse } from './models/TransactionResponse';
export type { UpdateCustomerDto } from './models/UpdateCustomerDto';
export type { UpdateDailyNoteDto } from './models/UpdateDailyNoteDto';
export type { UpdateSalesDto } from './models/UpdateSalesDto';
export type { UpdateSubscriptionDto } from './models/UpdateSubscriptionDto';
export { UpdateTransactionDto } from './models/UpdateTransactionDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UserAddOnSalesResponse } from './models/UserAddOnSalesResponse';
export { UserInfoResponse } from './models/UserInfoResponse';
export type { UserSalesReport } from './models/UserSalesReport';
export type { UseServiceDto } from './models/UseServiceDto';

export { AddOnsService } from './services/AddOnsService';
export { AppService } from './services/AppService';
export { AuditLogService } from './services/AuditLogService';
export { AuthService } from './services/AuthService';
export { BrandService } from './services/BrandService';
export { CarService } from './services/CarService';
export { CustomerService } from './services/CustomerService';
export { DailyNotesService } from './services/DailyNotesService';
export { ImageService } from './services/ImageService';
export { IntegrationService } from './services/IntegrationService';
export { ModelService } from './services/ModelService';
export { SalesService } from './services/SalesService';
export { SeederService } from './services/SeederService';
export { ServiceService } from './services/ServiceService';
export { StatisticsService } from './services/StatisticsService';
export { SubscriptionService } from './services/SubscriptionService';
export { TechnicianService } from './services/TechnicianService';
export { TransactionService } from './services/TransactionService';
